version: '3'
services:
  nginx:
    build: docker/nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/logs/:/var/log/nginx
      - ./jobs:/var/www/jobs
  php:
    build: docker/php
    restart: always
    volumes:
      - ./jobs:/var/www/jobs
  db:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    volumes:
      - backend_refactoring_challenge_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobs
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  composer:
    image: composer:2.0
    volumes:
      - ./jobs/:/app
    command: install

volumes:
  backend_refactoring_challenge_db_data:
