services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    AppBundle\Services\EntityFactory\EntityFactoryInterface:
      tags: ['app_bundle.entity_factory']
    AppBundle\Services\EntityUpdater\EntityUpdaterInterface:
      tags: ['app_bundle.entity_updater']

  AppBundle\Services\:
    resource: '../../Services/*'

  AppBundle\Repository\:
    resource: '../../Repository/*'

  AppBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  AppBundle\Controller\AbstractController:
    abstract: true

  AppBundle\Services\Validator\EntityExistsConstraintValidator:
    tags:
      - { name: validator.constraint_validator }

  AppBundle\Services\EntityFactory\AbstractEntityFactory:
    arguments:
      $factories: !tagged app_bundle.entity_factory

  AppBundle\Services\EntityUpdater\AbstractEntityUpdater:
    arguments:
      $updaters: !tagged app_bundle.entity_updater

  AppBundle\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 1 }
