parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Services\:
        resource: '../../src/AppBundle/Services/*'

    AppBundle\Repository\:
        resource: '../../src/AppBundle/Repository/*'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        tags: ['controller.service_arguments']

    AppBundle\Controller\AbstractController:
        abstract: true

    AppBundle\Services\Validator\EntityExistsConstraintValidator:
        tags:
            - { name: validator.constraint_validator }
